feat: add top level download command
ethersphere/swarm-cli pull request #271
Opened 2021-10-21 12:43 UTC by Cafe137

2021-11-02 16:15 UTC, nugaon requested changes
Please rewrite the `address` argument's description from "Root manifest reference" to "Manifest reference (with optional path)" or smth.
Also create test for that use-case, when the `address` has this path.

2021-11-02 21:01 UTC, Cafe137 commented on src/command/download.ts
> +  public readonly aliases = ['dl']
I think `dl` is more widespread.

We can include both once I am done with multiple alias support in the core. 🙂

2021-11-03 10:53 UTC, nugaon approved these changes
Nice work!

2021-11-03 10:53 UTC, agazso commented
I'm trying to download the Swarm website (437b4a5f61b44ce6f6c69b4841fdec548d2dba1b664b2fb8b02489d680df9207) which has quite big files. The filenames are printed only after the file is downloaded and there is no indication of anything is happening. Also with the `-v` option I only see the `Downloading <filename>` message _after_ the file was downloaded.

It would be good to have at least a spinner or some indicator when the file is being downloaded. With the `-v` option it would be good if the `Downloading...` message were printed _before_ the file is downloaded.

2021-11-03 11:57 UTC, merged